---
resources:
  - name: fauna-go-repository
    type: git
    icon: github
    source:
      uri: git@github.com:parkhomenko/faunadb-go.git
      branch: oss-706-concourse-ci-automation
      private_key: ((fauna/repo.key))

jobs:
  - name: release
    serial: true
    public: false
    plan:
      - get: fauna-go-repository

      - task: integration-tests
        file: fauna-go-repository/concourse/tasks/integration-tests.yml
        privileged: true
        params:
          FAUNA_ROOT_KEY: ((fauna.secret))
          FAUNA_ENDPOINT: ((fauna.domain))

      - task: publish
        file: fauna-go-repository/concourse/tasks/publish.yml

      - put: fauna-go-repository
        params:
          repository: fauna-go-repository-updated
